# Generated by Django 4.0 on 2021-12-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Event Name')),
                ('start', models.TimeField(verbose_name='Event Starting Time')),
                ('end', models.TimeField(verbose_name='Event Starting Time')),
            ],
        ),
    ]
