# Generated by Django 4.0 on 2022-01-10 07:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.SmallIntegerField(default=0)),
                ('gameover', models.BooleanField(default=False, null=True, verbose_name='Game Over')),
                ('qualifiedround1', models.BooleanField(default=False, null=True, verbose_name='Qualified Round 1 ?')),
                ('qualifiedround2', models.BooleanField(default=False, null=True, verbose_name='Qualified Round 2 ?')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Event Name')),
                ('start', models.DateTimeField(verbose_name='Event Starting Time')),
                ('end', models.DateTimeField(verbose_name='Event Starting Time')),
            ],
        ),
        migrations.CreateModel(
            name='Round2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Started Time')),
                ('ended', models.DateTimeField(verbose_name='Ended Time')),
                ('cheater', models.BooleanField(default=False, null=True)),
                ('passed', models.BooleanField(default=False, null=True)),
                ('shape', models.CharField(max_length=10, null=True, verbose_name='Shape Assigned')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('customuser', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.customuser', verbose_name='Custom User')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Round1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Started Time')),
                ('ended', models.DateTimeField(blank=True, null=True, verbose_name='Ended Time')),
                ('attempt', models.SmallIntegerField(default=1, null=True, verbose_name='Attempt Number')),
                ('cheater', models.BooleanField(default=False, null=True, verbose_name='Is A Cheater')),
                ('gameover', models.BooleanField(default=False, null=True, verbose_name='Game Over ')),
                ('passed', models.BooleanField(default=False, null=True, verbose_name='Has Passed This Round')),
                ('customuser', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.customuser', verbose_name='Custom User')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='User')),
            ],
        ),
    ]
