# Generated by Django 4.0 on 2022-01-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round2',
            name='ended',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ended Time'),
        ),
    ]
