# Generated by Django 4.0 on 2022-01-02 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('event', '0002_alter_event_end_alter_event_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Round2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(verbose_name='Started Time')),
                ('ended', models.DateTimeField(verbose_name='Ended Time')),
                ('cheater', models.BooleanField(default=False, null=True)),
                ('passed', models.BooleanField(default=False, null=True)),
                ('shape', models.CharField(default='umbrella', max_length=10, verbose_name='Shape Assigned')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Round1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(verbose_name='Started Time')),
                ('ended', models.DateTimeField(verbose_name='Ended Time')),
                ('cheater', models.BooleanField(default=False, null=True)),
                ('passed', models.BooleanField(default=False, null=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='event.customuser', verbose_name='User')),
            ],
        ),
    ]
