# Generated by Django 4.0 on 2022-01-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_round2_ended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round2',
            name='event',
        ),
        migrations.AddField(
            model_name='round2',
            name='gameover',
            field=models.BooleanField(default=False, null=True, verbose_name='Game Over '),
        ),
    ]
