# Generated by Django 4.0 on 2022-01-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_remove_round2_event_round2_gameover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round2',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='round2',
            name='shape',
            field=models.CharField(max_length=50, null=True, verbose_name='Shape Assigned'),
        ),
    ]
