# Generated by Django 4.0 on 2022-01-02 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('event', '0003_customuser_round2_round1'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='round2',
            name='shape',
            field=models.CharField(default='crescent', max_length=10, verbose_name='Shape Assigned'),
        ),
    ]
