# Generated by Django 4.0 on 2022-01-02 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('event', '0004_customuser_user_alter_round2_shape'),
    ]

    operations = [
        migrations.AddField(
            model_name='round1',
            name='customuser',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.customuser', verbose_name='Custom User'),
        ),
        migrations.AddField(
            model_name='round2',
            name='customuser',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.customuser', verbose_name='Custom User'),
        ),
        migrations.AlterField(
            model_name='round1',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='round2',
            name='shape',
            field=models.CharField(default='heart', max_length=10, verbose_name='Shape Assigned'),
        ),
    ]
