# Generated by Django 4.0 on 2022-01-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_round2_image_alter_round2_shape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round2',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Uploaded Image'),
        ),
    ]
