# Generated by Django 4.0 on 2022-01-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_round1_customuser_round2_customuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='qualifiedround1',
            field=models.BooleanField(default=False, null=True, verbose_name='Qualified Round 1 ?'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='qualifiedround2',
            field=models.BooleanField(default=False, null=True, verbose_name='Qualified Round 2 ?'),
        ),
        migrations.AlterField(
            model_name='round2',
            name='shape',
            field=models.CharField(default='umbrella', max_length=10, verbose_name='Shape Assigned'),
        ),
    ]
