# Generated by Django 4.0 on 2022-01-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_round2_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='round2',
            name='uploaded',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
