# Generated by Django 4.0 on 2022-01-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_customuser_qualifiedround1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round2',
            name='shape',
            field=models.CharField(default='crescent', max_length=10, verbose_name='Shape Assigned'),
        ),
    ]
