# Generated by Django 4.0 on 2022-01-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_round2_uploaded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='score',
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.SmallIntegerField(null=True),
        ),
    ]
