# Generated by Django 4.0 on 2022-01-17 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_remove_customuser_score_customuser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round2',
            name='cheater',
        ),
        migrations.RemoveField(
            model_name='round2',
            name='gameover',
        ),
    ]
