# Generated by Django 4.0 on 2022-01-03 14:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_alter_round2_shape'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round1',
            name='event',
        ),
        migrations.AddField(
            model_name='customuser',
            name='gameover',
            field=models.BooleanField(default=False, null=True, verbose_name='Game Over'),
        ),
        migrations.AddField(
            model_name='round1',
            name='attempt',
            field=models.SmallIntegerField(default=1, null=True, verbose_name='Attempt Number'),
        ),
        migrations.AddField(
            model_name='round1',
            name='gameover',
            field=models.BooleanField(default=False, null=True, verbose_name='Game Over '),
        ),
        migrations.AlterField(
            model_name='round1',
            name='cheater',
            field=models.BooleanField(default=False, null=True, verbose_name='Is A Cheater'),
        ),
        migrations.AlterField(
            model_name='round1',
            name='ended',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ended Time'),
        ),
        migrations.AlterField(
            model_name='round1',
            name='passed',
            field=models.BooleanField(default=False, null=True, verbose_name='Has Passed This Round'),
        ),
        migrations.AlterField(
            model_name='round1',
            name='started',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Started Time'),
        ),
        migrations.AlterField(
            model_name='round2',
            name='shape',
            field=models.CharField(max_length=10, null=True, verbose_name='Shape Assigned'),
        ),
    ]
