# Generated by Django 4.0 on 2022-01-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='round1',
            name='attempt',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Attempt Number'),
        ),
    ]
