# Generated by Django 4.0 on 2022-01-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_alter_customuser_phone_alter_round1_attempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round1',
            name='attempt',
            field=models.SmallIntegerField(default=1, null=True, verbose_name='Attempt Number'),
        ),
    ]
