# Generated by Django 4.0 on 2022-01-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_alter_round1_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='round1',
            field=models.BooleanField(default=False, verbose_name='Round1 started ?'),
        ),
        migrations.AddField(
            model_name='event',
            name='round2',
            field=models.BooleanField(default=False, verbose_name='Round2 started ?'),
        ),
    ]
