# Generated by Django 4.0 on 2022-01-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_event_round1_event_round2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round2',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Uploaded Image'),
        ),
    ]
